adminapp/urls.py
from django.urls import path
from adminapp.views import CategoriesListView, CategoryCreateView, CategoryDeleteView, CategoryUpdateView, IndexTemplateView, ProductCreateView, ProductDeleteView, ProductListView, ProductUpdateView, UserDeleteView, UserListView, UserCreateView, UserUpdateView


app_name = 'adminapp'

urlpatterns = [
    #     path('', index, name='index'),
    path('', IndexTemplateView.as_view(), name='index'),

    #     path('users/', admin_users, name='admin_users'),
    path('users/', UserListView.as_view(), name='admin_users'),

    #     path('user-create/', admin_user_create, name='admin_user_create'),
    path('user-create/', UserCreateView.as_view(), name='admin_user_create'),

    #     path('user-update/<int:id>/', admin_user_update, name='admin_user_update'),
    path('user-update/<int:pk>/', UserUpdateView.as_view(),
         name='admin_user_update'),

    #     path('user-delete/<int:id>/', admin_user_delete, name='admin_user_delete'),
    path('user-delete/<int:pk>/', UserDeleteView.as_view(),
         name='admin_user_delete'),

    #     path('categories/', admin_categories, name='admin_categories'),
    path('categories/', CategoriesListView.as_view(), name='admin_categories'),

    #     path('category-create/', admin_category_create, name='admin_category_create'),
    path('category-create/', CategoryCreateView.as_view(),
         name='admin_category_create'),

    #     path('category-update/<int:id>/', admin_category_update, name='admin_category_update'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(),
         name='admin_category_update'),

    #     path('category-delete/<int:id>/', admin_category_delete,name='admin_category_delete'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(),
         name='admin_category_delete'),

    #     path('products/', admin_products, name='admin_products'),
    path('products/', ProductListView.as_view(), name='admin_products'),

    #     path('product-create/', admin_product_create, name='admin_product_create'),
    path('product-create/', ProductCreateView.as_view(),
         name='admin_product_create'),

    #     path('product-update/<int:id>/', admin_product_update,name='admin_product_update'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(),
         name='admin_product_update'),

    #     path('product-delete/<int:id>/', admin_product_delete,name='admin_product_delete'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(),
         name='admin_product_delete'),

]

authapp/urls.py
from django.urls import path
from authapp.views import LoginGBView, ProfileFormView, RegisterView, Logout


app_name = 'authapp'

urlpatterns = [
    # path('login/', login, name='login'),
    path('login/', LoginGBView.as_view(), name='login'),

    # path('register/', register, name='register'),
    path('register/', RegisterView.as_view(), name='register'),

    # path('logout/', logout, name='logout'),
    path('logout/', Logout.as_view(), name='logout'),

    # path('profile/', profile, name='profile'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activate_key>/',
         RegisterView.verify, name='verify')

]

basket/urls.py
from unicodedata import name
from django.urls import path

from basket.views import basket_add, basket_remove, basket_edit

app_name = 'basket'

urlpatterns = [
    path('add/<int:id>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>', basket_remove, name='basket_remove'),
    path('edit/<int:basket_id>/<int:quantity>/',
         basket_edit, name='basket_edit')
]

geekshop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from mainapp.views import index


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('ordersapp/', include('ordersapp.urls', namespace='orders')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SERVER == False:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    ]

urlpatterns += [path('debug/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.models import User
from adminapp.forms import CategoryAdminCreateForm, CategoryAdminUpdateForm, ProductAdminCreateForm, UserAdminProfileForm, UserAdminRegisterForm
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from adminapp.mixin import BaseClassContextMixin, CustomDispatchMixin

from mainapp.models import Product, ProductCategories

# Пагинация
from django.core.paginator import Paginator

# Модули для CBV
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, TemplateView
from django.urls import reverse_lazy

# Create your views here.


# @user_passes_test(lambda u: u.is_superuser)
# def index(request):

#     context = {
#         'title': 'Админка',
#     }

#     return render(request, 'adminapp/admin.html', context)


class IndexTemplateView(TemplateView):

    template_name = 'adminapp/admin.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(IndexTemplateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IndexTemplateView, self).get_context_data(**kwargs)
        context['title'] = 'Админка'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users(request):

#     context = {
#         'title': 'Админка | Пользователи',
#         'users': User.objects.all(),
#     }

#     return render(request, 'adminapp/admin-users-read.html', context)


class UserListView(ListView, BaseClassContextMixin, CustomDispatchMixin):

    model = User
    template_name = 'adminapp/admin-users-read.html'
    title = 'Админка | Пользователи'
    context_object_name = 'users'


# @user_passes_test(lambda u: u.is_superuser)
# def admin_user_create(request):

#     if request.method == 'POST':
#         form = UserAdminRegisterForm(data=request.POST, files=request.FILES)
#         if form.is_valid:
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:admin_users'))
#         else:
#             print(form.errors)
#     else:
#         form = UserAdminRegisterForm()

#     context = {
#         'title': 'Админка | Регистрация',
#         'form': form,
#     }

#     return render(request, 'adminapp/admin-users-create.html', context)


class UserCreateView(CreateView, BaseClassContextMixin, CustomDispatchMixin):

    model = User
    template_name = 'adminapp/admin-users-create.html'
    title = 'Админка | Регистрация'
    form_class = UserAdminRegisterForm
    success_url = reverse_lazy('adminapp:admin_users')


# @user_passes_test(lambda u: u.is_superuser)
# def admin_user_update(request, id):

#     user_select = User.objects.get(id=id)

#     if request.method == 'POST':
#         form = UserAdminProfileForm(
#             data=request.POST, instance=user_select, files=request.FILES)
#         if form.is_valid:
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:admin_users'))
#     else:
#         form = UserAdminProfileForm(instance=user_select)

#     context = {
#         'title': 'Админка | Обновление пользователя',
#         "form": form,
#         'user_select': user_select,
#     }

#     return render(request, 'adminapp/admin-users-update-delete.html', context)


class UserUpdateView(UpdateView, BaseClassContextMixin, CustomDispatchMixin):

    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    form_class = UserAdminProfileForm
    title = 'Админка | Обновление пользователя'
    success_url = reverse_lazy('adminapp:admin_users')


# @user_passes_test(lambda u: u.is_superuser)
# def admin_user_delete(request, id):

#     # Удаление пользователя
#     # user = User.objects.get(id=id).delete()

#     # Делаем пользователя неактивным вместо удаления учётной записи.
#     user = User.objects.get(id=id)
#     user.is_active = False
#     user.save()
#     return HttpResponseRedirect(reverse('adminapp:admin_users'))


class UserDeleteView(DeleteView, CustomDispatchMixin):

    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    form_class = UserAdminProfileForm
    success_url = reverse_lazy('adminapp:admin_users')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False if self.object.is_active else True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda u: u.is_superuser)
# def admin_categories(request):

#     context = {
#         'title': 'Админка | Категории',
#         'categories': ProductCategories.objects.all(),
#     }

#     return render(request, 'adminapp/admin-categories-read.html', context)


class CategoriesListView(ListView, CustomDispatchMixin, BaseClassContextMixin):
    model = ProductCategories
    template_name = 'adminapp/admin-categories-read.html'
    title = 'Админка | Категории'
    context_object_name = 'categories'


# @user_passes_test(lambda u: u.is_superuser)
# def admin_category_create(request):

#     if request.method == 'POST':
#         form = CategoryAdminCreateForm(data=request.POST)
#         if form.is_valid:
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:admin_categories'))
#         else:
#             print(form.errors)
#     else:
#         form = CategoryAdminCreateForm()

#     context = {
#         'title': 'Админка | Новая категория',
#         'form': form,
#     }

#     return render(request, 'adminapp/admin-categories-create.html', context)


class CategoryCreateView(CreateView, CustomDispatchMixin, BaseClassContextMixin):
    model = ProductCategories
    template_name = 'adminapp/admin-categories-create.html'
    title = 'Админка | Новая категория'
    form_class = CategoryAdminCreateForm
    success_url = reverse_lazy('adminapp:admin_categories')


# @user_passes_test(lambda u: u.is_superuser)
# def admin_category_update(request, id):

#     category_select = ProductCategories.objects.get(id=id)

#     if request.method == 'POST':
#         form = CategoryAdminUpdateForm(
#             data=request.POST, instance=category_select)
#         if form.is_valid:
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:admin_categories'))
#         else:
#             print(form.errors)
#     else:
#         form = CategoryAdminUpdateForm(instance=category_select)

#     context = {
#         'title': 'Админка | Обновление категории',
#         'form': form,
#         'category_select': category_select,
#     }

#     return render(request, 'adminapp/admin-categories-update-delete.html', context)


class CategoryUpdateView(UpdateView, CustomDispatchMixin, BaseClassContextMixin):

    model = ProductCategories
    template_name = 'adminapp/admin-categories-update-delete.html'
    title = 'Админка | Обновление категории'
    form_class = CategoryAdminUpdateForm
    success_url = reverse_lazy('adminapp:admin_categories')
    context_object_name = 'category_select'


# @user_passes_test(lambda u: u.is_superuser)
# def admin_category_delete(request, id):
#     category = ProductCategories.objects.get(id=id).delete()
#     return HttpResponseRedirect(reverse('adminapp:admin_categories'))


class CategoryDeleteView(DeleteView, CustomDispatchMixin):

    model = ProductCategories
    template_name = 'adminapp/admin-categories-update-delete.html'
    success_url = reverse_lazy('adminapp:admin_categories')


# @user_passes_test(lambda u: u.is_superuser)
# def admin_products(request):

#     product_select = Product.objects.all()

#     context = {
#         'title': 'Админка | Продукты',
#         'product_select': product_select
#     }

#     return render(request, 'adminapp/admin-products-read.html', context)


class ProductListView(ListView, CustomDispatchMixin, BaseClassContextMixin):

    model = Product
    template_name = 'adminapp/admin-products-read.html'
    title = 'Админка | Продукты'
    context_object_name = 'product_select'


# @user_passes_test(lambda u: u.is_superuser)
# def admin_product_create(request):

#     if request.method == 'POST':
#         form = ProductAdminCreateForm(data=request.POST, files=request.FILES)
#         if form.is_valid:
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:admin_products'))
#         else:
#             print(form.errors)
#     else:
#         form = ProductAdminCreateForm()

#     context = {
#         'title': 'Админка | Новый продукт',
#         'form': form,
#     }

#     return render(request, 'adminapp/admin-products-create.html', context)


class ProductCreateView(CreateView, CustomDispatchMixin, BaseClassContextMixin):

    model = Product
    template_name = 'adminapp/admin-products-create.html'
    title = 'Админка | Новый продукт'
    form_class = ProductAdminCreateForm
    success_url = reverse_lazy('adminapp:admin_products')


# @user_passes_test(lambda u: u.is_superuser)
# def admin_product_update(request, id):

#     product_select = Product.objects.get(id=id)

#     if request.method == 'POST':
#         form = ProductAdminCreateForm(
#             data=request.POST, instance=product_select, files=request.FILES)
#         if form.is_valid:
#             form.save()
#             return HttpResponseRedirect(reverse('adminapp:admin_products'))
#         else:
#             print(form.errors)
#     else:
#         form = ProductAdminCreateForm(instance=product_select)

#     context = {
#         'title': 'Админка | Обновление продукта',
#         'form': form,
#         'product_select': product_select,
#     }

#     return render(request, 'adminapp/admin-products-update-delete.html', context)

adminapp/templates/adminapp/admin-categories-create.html
{% extends 'adminapp/base.html' %}

{% block context %}
<div class="container-fluid">
    <h1 class="mt-4">Создание категории</h1>
    <form action="{% url 'adminapp:admin_category_create' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Категория</label>
                    {{ form.name }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.descriptions.id_for_label }}">Описание</label>
                    {{ form.descriptions }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
</div>
{% endblock %}

adminapp/templates/adminapp/admin-categories-read.html
{% extends 'adminapp/base.html' %}

{% block context %}
<div class="container-fluid">
    <h1 class="mt-4">Категории</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Категории
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Название категории</th>
                            <th>Описание</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Название категории</th>
                            <th>Описание</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for category in categories %}
                        <tr>
                            <td><a href="{% url 'adminapp:admin_category_update' category.id %}"
                                    style="color: dodgerblue">{{ category.name }}</a></td>
                            <td>{{ category.descriptions }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'adminapp:admin_category_create' %}">
                <button class="btn btn-success">Создать категорию</button>
            </a>
        </div>
    </div>
</div>
{% endblock context %}

adminapp/templates/adminapp/admin-categories-update-delete.html
{% extends 'adminapp/base.html' %}


{% block context %}
<div class="container-fluid">
    <h1 class="mt-4">Редактирование категории | {{ category_select.name }}</h1>
    <div class="card-body">
        <form action="{% url 'adminapp:admin_category_update' category_select.id %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.name.id_for_label }}">Категория</label>
                        {{ form.name }}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.descriptions.id_for_label }}">Описание</label>
                        {{ form.descriptions }}
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <form action="{% url 'adminapp:admin_category_delete' category_select.id %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock context %}

adminapp/templates/adminapp/admin-products-read.html
{% extends 'adminapp/base.html' %}

{% block context %}
<div class="container-fluid">
    <h1 class="mt-4">Продукты</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Продукты
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Название продукта</th>
                            <th>Категория продукта</th>
                            <th>В наличии</th>
                            <th>Цена</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Название продукта</th>
                            <th>Категория продукта</th>
                            <th>В наличии</th>
                            <th>Цена</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for product in product_select %}
                        <tr>
                            <td><a href="{% url 'adminapp:admin_product_update' product.id %}"
                                    style="color: dodgerblue">{{ product.name }}</a></td>
                            <td>{{ product.price }} руб.</td>
                            <td>{{ product.quantity }}</td>
                            <td>{{ product.category }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'adminapp:admin_product_create' %}">
                <button class="btn btn-success">Создать продукт</button>
            </a>
        </div>
    </div>
</div>
{% endblock context %}

adminapp/templates/adminapp/admin-products-update-delete.html
{% extends 'adminapp/base.html' %}


{% block context %}
<div class="container-fluid">
    <h1 class="mt-4">Редактирование продукта | {{ product_select.name }}</h1>
    <div class="card-body">
        <form action="{% url 'adminapp:admin_product_update' product_select.id %}" method="post"
            enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row mb-2">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="form.name.id_for_label">Продукт</label>
                        {{ form.name }}
                    </div>
                </div>
            </div>

            {% if product_select.image %}
            <div class="col-lg-6" style="text-align: center;">
                <img src="{{ product_select.image.url }}" alt="" width="150">
            </div>
            {% endif %}

            <div class="form-row mb-4">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {% if not product_select.image %}<p>Выберите изображение:</p>{% endif %}
                        {{ form.image }}
                        <!-- <label class="custom-file-label" for="form.image.id_for_label">Выберите изображение</label> -->
                    </div>
                </div>
            </div>
            <div class="form-row mb-4">
                <div class="col-lg-6">
                    <label class="small mb-1" for="form.descriptions.id_for_label">Описание</label>
                    {{ form.descriptions }}
                </div>
            </div>
            <div class="form-row mb-4">
                <div class="col-lg-6">
                    <label class="small mb-1" for="form.price.id_for_label">Цена</label>
                    {{ form.price }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="form.quantity.id_for_label">Количество</label>
                    {{ form.quantity }}
                </div>
            </div>
            <div class="form-row mb-4">
                <div class="col-lg-6">
                    <label class="small mb-1" for="form.category.id_for_label">Категория</label>
                    {{ form.category }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <form action="{% url 'adminapp:admin_product_delete' product_select.id %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock context %}

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}

{% block context %}

<div class="container-fluid">
    <h1 class="mt-4">Пользователи</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Пользователи
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                        </tr>
                    </tfoot>
                    <tbody>

                        {% for user in users %}
                        <tr>
                            <td><a href="{% url 'adminapp:admin_user_update' user.id %}" style="color: dodgerblue">
                                    {{ user.username }}
                                </a></td>
                            <td>{{user.first_name}}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.is_staff %}
                                <i class="fas fa-check-circle"></i>
                                {% else %}
                                <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if user.is_active %}
                                <i class="fas fa-check-circle"></i>
                                {% else %}
                                <i class="fas fa-times-circle"></i>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'adminapp:admin_user_create' %}">
                <button class="btn btn-success">Создать пользователя</button>
            </a>
        </div>
    </div>
</div>

{% endblock context %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}

{% block context %}

<div class="container-fluid">
    <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body">
        <form action="{% url 'adminapp:admin_user_update' user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row mb-4">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{form.last_name.id_for_label}}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>

            {% if user.image %}
            <div class="col-lg-6 mb-4" style="text-align: center;">
                <img src="{{ user.image.url }}" alt="" width="150">
            </div>
            {% endif %}

            <div class="form-row mb-4">
                <div class="col-lg-12">
                    <div class="custom-file">
                        <label>
                            {% if not user.image %}<p>Выберите изображение:</p>{% endif %}
                            {{ form.image }}
                        </label>
                        <!-- <label class="custom-file-label" for="{{ form.image.id_for_label }}"></label> -->
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-4">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-4">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
                <div class="col-lg-4">
                    <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                    {{ form.age }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <form action="{% url 'adminapp:admin_user_delete' user.id %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock context %}

adminapp/templates/adminapp/admin.html
{% extends 'adminapp/base.html' %}
{% block context %}
<div class="container-fluid">
    <h1 class="mt-4">Административная панель</h1>
</div>
{% endblock %}